import type { Transaction, TransactionGroup } from '../types';
import { formatDateKey, parseDateKey } from './date';

const RECURRING_GROUPS: TransactionGroup[] = ['operational', 'loan', 'personal'];

// Default tokens (substrings) to NEVER suggest when filling next month.
// These are typically one-off purchases or descriptions the user marked
// as not recurring. The user can extend this list at runtime via
// addToAutoFillBlacklist() in storageService.
export const DEFAULT_AUTOFILL_BLACKLIST: string[] = [
  'אייפד',
  'iPad',
  'חיובי חו"ל',
  'חיובי חוץ',
  'היימן',
  'קומפלקס כימיקלים',
  'להבין על מה ההוצאה מול ליאור',
  'מונית ולדה',
  'מחשב נייח - נויה',
  'מסלול ערוץ',
  'נסיעות - מוניות',
  'ריבית רבעונית',
  'ISO 27001',
  'iso27001',
];

const normalize = (value: string | undefined | null) =>
  (value || '')
    .toLowerCase()
    .replace(/[\s"'\-_.]/g, '');

const matchesBlacklist = (description: string, category: string, blacklist: string[]): boolean => {
  const haystack = `${normalize(description)} ${normalize(category)}`;
  return blacklist.some(token => {
    const t = normalize(token);
    return t.length > 0 && haystack.includes(t);
  });
};

export type AutoFillSuggestion = {
  key: string;
  description: string;
  category: string;
  group: TransactionGroup;
  averageAmount: number;
  monthlyAmounts: number[]; // amounts from the lookback months (one entry per occurrence)
  monthsAppeared: string[]; // YYYY-MM keys where this transaction was seen
  proposedDate: string; // YYYY-MM-DD
  paymentMethod: Transaction['paymentMethod'];
  loanEndMonth?: string;
  alreadyExistsInTargetMonth: boolean;
  type: Transaction['type'];
};

const monthKey = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;

const dayOfMonth = (dateStr: string) => parseDateKey(dateStr).getDate();

const lastDayOfMonth = (year: number, monthZeroBased: number) =>
  new Date(year, monthZeroBased + 1, 0).getDate();

const buildProposedDate = (
  targetYear: number,
  targetMonth: number,
  preferredDay: number,
): string => {
  const maxDay = lastDayOfMonth(targetYear, targetMonth);
  const safeDay = Math.min(preferredDay, maxDay);
  return formatDateKey(new Date(targetYear, targetMonth, safeDay, 12));
};

const isLoanStillActive = (
  loanEndMonth: string | undefined,
  targetYear: number,
  targetMonth: number,
): boolean => {
  if (!loanEndMonth) return true;
  const [endYearStr, endMonthStr] = loanEndMonth.split('-');
  const endYear = parseInt(endYearStr, 10);
  const endMonth = parseInt(endMonthStr, 10) - 1;
  if (Number.isNaN(endYear) || Number.isNaN(endMonth)) return true;
  // Loan still active if its end month is on/after the target month
  if (endYear > targetYear) return true;
  if (endYear < targetYear) return false;
  return endMonth >= targetMonth;
};

/**
 * Build proposed transactions for the target month based on the previous 3 calendar months.
 * Includes operational, loan, and personal groups only. Skips auto-generated entries.
 * Excludes any transaction whose description/category matches the blacklist.
 */
export const computeNextMonthSuggestions = (
  transactions: Transaction[],
  target: { year: number; month: number }, // month is 0-indexed
  userBlacklist: string[] = [],
): AutoFillSuggestion[] => {
  const fullBlacklist = [...DEFAULT_AUTOFILL_BLACKLIST, ...userBlacklist];
  const targetMonthKey = `${target.year}-${String(target.month + 1).padStart(2, '0')}`;

  // Determine the 3 lookback months (calendar months immediately preceding target)
  const lookbackKeys: string[] = [];
  for (let i = 1; i <= 3; i += 1) {
    const d = new Date(target.year, target.month - i, 1);
    lookbackKeys.push(monthKey(d));
  }
  const lookbackSet = new Set(lookbackKeys);

  type Bucket = {
    key: string;
    description: string;
    category: string;
    group: TransactionGroup;
    type: Transaction['type'];
    paymentMethod: Transaction['paymentMethod'];
    monthlyAmounts: number[];
    monthsAppeared: Set<string>;
    latestDayOfMonth: number;
    latestSeenAt: Date;
    loanEndMonth?: string;
  };

  const buckets = new Map<string, Bucket>();

  // Track existing transactions in the target month to flag duplicates
  const targetMonthSignatures = new Set<string>();

  transactions.forEach(t => {
    if (!RECURRING_GROUPS.includes(t.group)) return;
    if (t.isAutoGenerated) return;
    if (t.type !== 'expense') return;

    const tDate = parseDateKey(t.date);
    const tMonthKey = monthKey(tDate);

    if (tMonthKey === targetMonthKey) {
      targetMonthSignatures.add(`${(t.description || '').trim()}|${(t.category || '').trim()}|${t.group}`);
      return;
    }

    if (!lookbackSet.has(tMonthKey)) return;

    // For loans, skip if loan ended before the target month
    if (t.group === 'loan' && !isLoanStillActive(t.loanEndMonth, target.year, target.month)) return;

    // Skip blacklisted descriptions/categories
    if (matchesBlacklist(t.description || '', t.category || '', fullBlacklist)) return;

    const description = (t.description || '').trim() || '(ללא תיאור)';
    const category = (t.category || '').trim() || '(ללא קטגוריה)';
    const key = `${description}|${category}|${t.group}`;
    const amount = Math.abs(Number(t.amount) || 0);

    const existing = buckets.get(key);
    if (existing) {
      existing.monthlyAmounts.push(amount);
      existing.monthsAppeared.add(tMonthKey);
      if (tDate.getTime() > existing.latestSeenAt.getTime()) {
        existing.latestSeenAt = tDate;
        existing.latestDayOfMonth = dayOfMonth(t.date);
        existing.paymentMethod = t.paymentMethod;
        existing.loanEndMonth = t.loanEndMonth;
      }
    } else {
      buckets.set(key, {
        key,
        description,
        category,
        group: t.group,
        type: t.type,
        paymentMethod: t.paymentMethod,
        monthlyAmounts: [amount],
        monthsAppeared: new Set([tMonthKey]),
        latestDayOfMonth: dayOfMonth(t.date),
        latestSeenAt: tDate,
        loanEndMonth: t.loanEndMonth,
      });
    }
  });

  const suggestions: AutoFillSuggestion[] = [];
  buckets.forEach(b => {
    const occurrenceCount = b.monthlyAmounts.length;
    const average =
      occurrenceCount > 0
        ? b.monthlyAmounts.reduce((sum, n) => sum + n, 0) / occurrenceCount
        : 0;
    const proposedDate = buildProposedDate(target.year, target.month, b.latestDayOfMonth);
    const signature = `${b.description}|${b.category}|${b.group}`;
    const alreadyExists = targetMonthSignatures.has(signature);

    suggestions.push({
      key: b.key,
      description: b.description === '(ללא תיאור)' ? '' : b.description,
      category: b.category === '(ללא קטגוריה)' ? '' : b.category,
      group: b.group,
      type: b.type,
      paymentMethod: b.paymentMethod,
      averageAmount: Math.round(average * 100) / 100,
      monthlyAmounts: b.monthlyAmounts,
      monthsAppeared: Array.from(b.monthsAppeared).sort(),
      proposedDate,
      loanEndMonth: b.loanEndMonth,
      alreadyExistsInTargetMonth: alreadyExists,
    });
  });

  // Sort by group then description
  const groupOrder: Record<TransactionGroup, number> = {
    fee: 0,
    other_income: 1,
    operational: 2,
    tax: 3,
    loan: 4,
    personal: 5,
    bank_adjustment: 6,
  };
  suggestions.sort((a, b) => {
    const g = (groupOrder[a.group] ?? 99) - (groupOrder[b.group] ?? 99);
    if (g !== 0) return g;
    return a.description.localeCompare(b.description, 'he');
  });

  return suggestions;
};

export const getDefaultTargetMonth = (today = new Date()): { year: number; month: number } => {
  const next = new Date(today.getFullYear(), today.getMonth() + 1, 1);
  return { year: next.getFullYear(), month: next.getMonth() };
};

export const formatTargetMonthLabel = (target: { year: number; month: number }): string => {
  const date = new Date(target.year, target.month, 1);
  return date.toLocaleDateString('he-IL', { month: 'long', year: 'numeric' });
};

export const formatLookbackLabel = (target: { year: number; month: number }): string => {
  const labels: string[] = [];
  for (let i = 3; i >= 1; i -= 1) {
    const d = new Date(target.year, target.month - i, 1);
    labels.push(d.toLocaleDateString('he-IL', { month: 'long' }));
  }
  return labels.join(' / ');
};
