import React, { useMemo, useState, useEffect } from 'react';
import { X, Wand2, AlertCircle, Ban } from 'lucide-react';
import type { Transaction, TransactionGroup } from '../types';
import {
  computeNextMonthSuggestions,
  getDefaultTargetMonth,
  formatTargetMonthLabel,
  formatLookbackLabel,
  DEFAULT_AUTOFILL_BLACKLIST,
  type AutoFillSuggestion,
} from '../utils/nextMonthAutoFill';
import { lightInputCompactClasses } from './ui/inputStyles';
import {
  getUserAutoFillBlacklist,
  addToAutoFillBlacklist,
  removeFromAutoFillBlacklist,
  STORAGE_EVENT,
} from '../services/storageService';

interface NextMonthAutoFillModalProps {
  isOpen: boolean;
  onClose: () => void;
  transactions: Transaction[];
  onConfirm: (newTransactions: Omit<Transaction, 'id'>[]) => void;
}

const GROUP_LABELS: Record<TransactionGroup, string> = {
  fee: 'שכר טרחה',
  other_income: 'הכנסות אחרות',
  operational: 'הוצאות',
  tax: 'מיסים',
  loan: 'הלוואות',
  personal: 'משיכות',
  bank_adjustment: 'התאמת בנק',
};

const GROUP_COLORS: Record<TransactionGroup, string> = {
  fee: 'bg-emerald-100 text-emerald-700',
  other_income: 'bg-teal-100 text-teal-700',
  operational: 'bg-amber-100 text-amber-700',
  tax: 'bg-yellow-100 text-yellow-700',
  loan: 'bg-rose-100 text-rose-700',
  personal: 'bg-pink-100 text-pink-700',
  bank_adjustment: 'bg-slate-100 text-slate-700',
};

type EditedRow = {
  amount: number;
  date: string;
};

const NextMonthAutoFillModal: React.FC<NextMonthAutoFillModalProps> = ({
  isOpen,
  onClose,
  transactions,
  onConfirm,
}) => {
  const target = useMemo(() => getDefaultTargetMonth(), []);
  const targetLabel = useMemo(() => formatTargetMonthLabel(target), [target]);
  const lookbackLabel = useMemo(() => formatLookbackLabel(target), [target]);
  const [userBlacklist, setUserBlacklist] = useState<string[]>(() => getUserAutoFillBlacklist());
  const [showBlacklistManager, setShowBlacklistManager] = useState(false);

  useEffect(() => {
    const handler = () => setUserBlacklist(getUserAutoFillBlacklist());
    window.addEventListener(STORAGE_EVENT, handler);
    return () => window.removeEventListener(STORAGE_EVENT, handler);
  }, []);

  const suggestions = useMemo(
    () => computeNextMonthSuggestions(transactions, target, userBlacklist),
    [transactions, target, userBlacklist],
  );

  const [selectedKeys, setSelectedKeys] = useState<Set<string>>(new Set());
  const [edited, setEdited] = useState<Record<string, EditedRow>>({});

  useEffect(() => {
    if (!isOpen) return;
    // Pre-select everything that does not already exist in the target month
    const initialSelected = new Set<string>();
    const initialEdited: Record<string, EditedRow> = {};
    suggestions.forEach(s => {
      if (!s.alreadyExistsInTargetMonth) initialSelected.add(s.key);
      initialEdited[s.key] = { amount: s.averageAmount, date: s.proposedDate };
    });
    setSelectedKeys(initialSelected);
    setEdited(initialEdited);
  }, [isOpen, suggestions]);

  if (!isOpen) return null;

  const toggleKey = (key: string) => {
    setSelectedKeys(prev => {
      const next = new Set(prev);
      if (next.has(key)) next.delete(key);
      else next.add(key);
      return next;
    });
  };

  const updateAmount = (key: string, value: string) => {
    const parsed = Number(value.replace(/[, ₪]/g, ''));
    if (!Number.isFinite(parsed)) return;
    setEdited(prev => ({ ...prev, [key]: { ...prev[key], amount: parsed } }));
  };

  const updateDate = (key: string, value: string) => {
    setEdited(prev => ({ ...prev, [key]: { ...prev[key], date: value } }));
  };

  const handleBlacklist = (description: string) => {
    if (!description.trim()) return;
    addToAutoFillBlacklist(description.trim());
    setUserBlacklist(getUserAutoFillBlacklist());
  };

  const handleUnblacklist = (item: string) => {
    removeFromAutoFillBlacklist(item);
    setUserBlacklist(getUserAutoFillBlacklist());
  };

  const selectedSuggestions = suggestions.filter(s => selectedKeys.has(s.key));
  const selectedTotal = selectedSuggestions.reduce(
    (sum, s) => sum + (edited[s.key]?.amount ?? s.averageAmount),
    0,
  );

  const handleConfirm = () => {
    const newTransactions: Omit<Transaction, 'id'>[] = selectedSuggestions.map(s => {
      const e = edited[s.key];
      return {
        date: e?.date ?? s.proposedDate,
        amount: Math.abs(e?.amount ?? s.averageAmount),
        type: 'expense',
        group: s.group,
        category: s.category,
        description: s.description,
        paymentMethod: s.paymentMethod,
        status: 'pending',
        loanEndMonth: s.group === 'loan' ? s.loanEndMonth : undefined,
        isAutoGenerated: false,
        isManualOverride: false,
      };
    });
    onConfirm(newTransactions);
    onClose();
  };

  const renderCurrency = (value: number) =>
    `₪${value.toLocaleString('he-IL', { maximumFractionDigits: 0 })}`;

  const formatRange = (s: AutoFillSuggestion) => {
    if (s.monthlyAmounts.length === 0) return '';
    const min = Math.min(...s.monthlyAmounts);
    const max = Math.max(...s.monthlyAmounts);
    if (min === max) return `${renderCurrency(min)} בכל חודש`;
    return `${renderCurrency(min)} - ${renderCurrency(max)}`;
  };

  return (
    <div className="fixed inset-0 z-50 flex items-start justify-center bg-slate-900/70 backdrop-blur-sm p-4 overflow-y-auto pt-12">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-5xl border border-slate-200">
        <div className="p-6 border-b border-slate-100 flex items-start justify-between gap-4">
          <div>
            <h2 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
              <Wand2 className="w-6 h-6 text-violet-600" />
              מילוי אוטומטי - {targetLabel}
            </h2>
            <p className="text-sm text-slate-500 mt-1">
              הצעות לפי ממוצע 3 חודשים אחרונים ({lookbackLabel}). כולל הוצאות, הלוואות, משיכות. רק תנועות מסומנות ייווספו, בסטטוס "צפוי". אפשר לערוך סכום ותאריך לפני אישור.
            </p>
          </div>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-slate-600 transition-colors"
            aria-label="סגור"
          >
            <X className="w-6 h-6" />
          </button>
        </div>

        {suggestions.length === 0 ? (
          <div className="p-12 text-center">
            <AlertCircle className="w-10 h-10 text-slate-300 mx-auto mb-3" />
            <p className="text-slate-500">
              לא נמצאו הוצאות, הלוואות או משיכות חוזרות ב-3 החודשים האחרונים.
            </p>
            <p className="text-xs text-slate-400 mt-2">
              חודשים שנבדקו: {lookbackLabel}
            </p>
          </div>
        ) : (
          <>
            <div className="overflow-x-auto max-h-[55vh]">
              <table className="w-full text-sm">
                <thead className="bg-slate-50 text-slate-500 sticky top-0">
                  <tr>
                    <th className="text-center px-3 py-2 font-medium w-12">בחר</th>
                    <th className="text-right px-3 py-2 font-medium">תיאור</th>
                    <th className="text-right px-3 py-2 font-medium">קטגוריה</th>
                    <th className="text-right px-3 py-2 font-medium">תאריך מוצע</th>
                    <th className="text-right px-3 py-2 font-medium">סכום מוצע</th>
                    <th className="text-right px-3 py-2 font-medium">הופיע ב</th>
                    <th className="text-right px-3 py-2 font-medium">טווח סכומים</th>
                    <th className="text-center px-3 py-2 font-medium w-24">פעולה</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {suggestions.map(s => {
                    const isSelected = selectedKeys.has(s.key);
                    const e = edited[s.key];
                    return (
                      <tr
                        key={s.key}
                        className={`hover:bg-slate-50 ${s.alreadyExistsInTargetMonth ? 'bg-amber-50/30' : ''}`}
                      >
                        <td className="px-3 py-2 text-center">
                          <input
                            type="checkbox"
                            checked={isSelected}
                            onChange={() => toggleKey(s.key)}
                            className="w-4 h-4 accent-violet-600 cursor-pointer"
                          />
                        </td>
                        <td className="px-3 py-2 text-slate-700 font-medium">
                          {s.description || '(ללא תיאור)'}
                          {s.alreadyExistsInTargetMonth && (
                            <span className="mr-2 inline-block text-[10px] bg-amber-100 text-amber-700 px-1.5 py-0.5 rounded">
                              כבר קיים בחודש היעד
                            </span>
                          )}
                        </td>
                        <td className="px-3 py-2">
                          <span className={`inline-block text-[11px] px-2 py-0.5 rounded ${GROUP_COLORS[s.group]}`}>
                            {s.category || GROUP_LABELS[s.group]}
                          </span>
                        </td>
                        <td className="px-3 py-2">
                          <input
                            type="date"
                            value={e?.date ?? s.proposedDate}
                            onChange={(ev) => updateDate(s.key, ev.target.value)}
                            disabled={!isSelected}
                            className={`${lightInputCompactClasses} w-auto disabled:opacity-50`}
                          />
                        </td>
                        <td className="px-3 py-2">
                          <input
                            type="number"
                            value={e?.amount ?? s.averageAmount}
                            onChange={(ev) => updateAmount(s.key, ev.target.value)}
                            disabled={!isSelected}
                            className={`${lightInputCompactClasses} w-28 disabled:opacity-50`}
                            min="0"
                            step="0.01"
                          />
                        </td>
                        <td className="px-3 py-2 text-xs text-slate-500">
                          {s.monthsAppeared.length}/3 חודשים
                        </td>
                        <td className="px-3 py-2 text-xs text-slate-500">{formatRange(s)}</td>
                        <td className="px-3 py-2 text-center">
                          <button
                            type="button"
                            onClick={() => handleBlacklist(s.description)}
                            className="text-[11px] inline-flex items-center gap-1 text-slate-500 hover:text-rose-700"
                            title="אל תציע יותר את התיאור הזה (אפשר לבטל מהניהול למטה)"
                          >
                            <Ban className="w-3 h-3" />
                            אל תציע
                          </button>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>

            <div className="px-6 py-3 border-t border-slate-100 bg-slate-50/30 text-xs text-slate-500 flex items-center justify-between flex-wrap gap-2">
              <div>
                סינון אוטומטי פעיל: {DEFAULT_AUTOFILL_BLACKLIST.length} תיאורים מובנים + {userBlacklist.length} משתמש.
              </div>
              <button
                type="button"
                onClick={() => setShowBlacklistManager(prev => !prev)}
                className="text-blue-600 hover:text-blue-800 font-semibold"
              >
                {showBlacklistManager ? 'הסתר ניהול חסימות' : 'נהל רשימת חסימות'}
              </button>
            </div>

            {showBlacklistManager && (
              <div className="px-6 py-4 border-t border-slate-100 bg-slate-50/60 space-y-3">
                <div>
                  <p className="text-xs font-semibold text-slate-700 mb-2">חסומים מובנים (לא ניתן להסיר):</p>
                  <div className="flex flex-wrap gap-1.5">
                    {DEFAULT_AUTOFILL_BLACKLIST.map(item => (
                      <span key={item} className="inline-block text-[11px] px-2 py-0.5 rounded bg-slate-200 text-slate-600">
                        {item}
                      </span>
                    ))}
                  </div>
                </div>
                {userBlacklist.length > 0 && (
                  <div>
                    <p className="text-xs font-semibold text-slate-700 mb-2">חסומים שלך ({userBlacklist.length}) - לחץ X להסיר:</p>
                    <div className="flex flex-wrap gap-1.5">
                      {userBlacklist.map(item => (
                        <span key={item} className="inline-flex items-center gap-1 text-[11px] px-2 py-0.5 rounded bg-rose-100 text-rose-700">
                          {item}
                          <button
                            type="button"
                            onClick={() => handleUnblacklist(item)}
                            className="hover:text-rose-900"
                            aria-label="הסר מרשימה"
                          >
                            <X className="w-3 h-3" />
                          </button>
                        </span>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            )}

            <div className="p-6 border-t border-slate-100 bg-slate-50/60 flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
              <div className="text-slate-700 text-sm">
                ייווסף: <span className="font-bold">{selectedSuggestions.length}</span> תנועות (סה"כ <span className="font-bold">{renderCurrency(selectedTotal)}</span>)
              </div>
              <div className="flex gap-2">
                <button
                  onClick={onClose}
                  className="px-5 py-2 text-sm font-semibold rounded-lg border border-slate-300 text-slate-700 hover:bg-slate-100"
                >
                  ביטול
                </button>
                <button
                  onClick={handleConfirm}
                  disabled={selectedSuggestions.length === 0}
                  className="px-5 py-2 text-sm font-semibold rounded-lg bg-violet-600 text-white hover:bg-violet-500 disabled:bg-slate-300 disabled:cursor-not-allowed"
                >
                  ✓ אישור והוספה ({selectedSuggestions.length})
                </button>
              </div>
            </div>
          </>
        )}
      </div>
    </div>
  );
};

export default NextMonthAutoFillModal;
