import type { Transaction } from '../types';
import { formatDateKey } from '../utils/date';

/**
 * This function takes the current list of transactions,
 * calculates the expected VAT and Income Tax for the NEXT month based on "Fee" income,
 * and upserts (updates or inserts) these tax transactions.
 */
export const syncTaxTransactions = (transactions: Transaction[]): Transaction[] => {
    // 1. Group Fee Income by Month (YYYY-MM)
    const monthlyFees: Record<string, number> = {};

    transactions.forEach(t => {
        if (t.type === 'income' && t.group === 'fee' && t.status === 'completed') {
            const date = new Date(t.date);
            const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;
            monthlyFees[key] = (monthlyFees[key] || 0) + t.amount;
        }
    });

    // 2. Create a map of existing auto-generated transactions to avoid duplication
    // Key: linkedMonth_taxType (e.g. "2024-01_vat")
    const existingAutoTaxes: Record<string, Transaction> = {};
    
    // We also need to keep track of manual transactions to not touch them,
    // but here we specifically look for ones we created (isAutoGenerated)
    const resultTransactions = [...transactions];

    resultTransactions.forEach(t => {
        if (t.isAutoGenerated && t.linkedMonth) {
            const key = `${t.linkedMonth}_${t.category}`; // category will be 'מע"מ' or 'מס הכנסה אישי'
            existingAutoTaxes[key] = t;
        }
    });

    // 3. Generate Taxes for Next Month
    Object.entries(monthlyFees).forEach(([monthKey, totalFee]) => {
        // Parse the monthKey (YYYY-MM)
        const [yearStr, monthStr] = monthKey.split('-');
        const incomeDate = new Date(parseInt(yearStr), parseInt(monthStr) - 1, 1);

        // Calculate Next Month
        const nextMonthDate = new Date(incomeDate);
        nextMonthDate.setMonth(nextMonthDate.getMonth() + 1);
        
        const nextYear = nextMonthDate.getFullYear();
        const nextMonth = nextMonthDate.getMonth(); // 0-11

        // Calculate Amounts
        const vatAmount = totalFee * 0.18;
        const taxAmount = totalFee * 0.0833;

        // Define Dates
        // VAT: 25th
        const vatDate = formatDateKey(new Date(nextYear, nextMonth, 25, 12, 0, 0));
        // Tax: 23rd
        const taxDate = formatDateKey(new Date(nextYear, nextMonth, 23, 12, 0, 0));

        // --- Handle VAT Transaction ---
        const vatKey = `${monthKey}_מע"מ`;
        const existingVat = existingAutoTaxes[vatKey];

        if (existingVat) {
            // Update only if not manually overridden
            if (!existingVat.isManualOverride) {
                existingVat.amount = parseFloat(vatAmount.toFixed(2));
                // We generally don't update date if it already exists, allowing user to move it slightly without full override flag,
                // but for strict auto-sync, we might reset date. Let's just update amount.
            }
        } else {
            // Create new VAT transaction
            resultTransactions.push({
                id: `auto_vat_${monthKey}_${Date.now()}`,
                date: vatDate,
                amount: parseFloat(vatAmount.toFixed(2)),
                type: 'expense',
                group: 'tax',
                category: 'מע"מ',
                description: `מע"מ אוטומטי (בגין ${monthStr}/${yearStr})`,
                paymentMethod: 'transfer',
                status: 'pending', // Future payment
                isAutoGenerated: true,
                linkedMonth: monthKey,
                isManualOverride: false
            });
        }

        // --- Handle Income Tax Transaction ---
        const taxKey = `${monthKey}_מס הכנסה אישי`;
        const existingTax = existingAutoTaxes[taxKey];

        if (existingTax) {
            if (!existingTax.isManualOverride) {
                existingTax.amount = parseFloat(taxAmount.toFixed(2));
            }
        } else {
            // Create new Tax transaction
            resultTransactions.push({
                id: `auto_tax_${monthKey}_${Date.now()}`,
                date: taxDate,
                amount: parseFloat(taxAmount.toFixed(2)),
                type: 'expense',
                group: 'tax',
                category: 'מס הכנסה אישי',
                description: `מקדמות מס (בגין ${monthStr}/${yearStr})`,
                paymentMethod: 'transfer',
                status: 'pending',
                isAutoGenerated: true,
                linkedMonth: monthKey,
                isManualOverride: false
            });
        }
    });

    const cleanedTransactions = resultTransactions.filter(t => {
        if (!t.isAutoGenerated || !t.linkedMonth) {
            return true;
        }

        if (t.isManualOverride) {
            return true;
        }

        return monthlyFees[t.linkedMonth] !== undefined;
    });

    return cleanedTransactions;
};