import { describe, it, expect } from 'vitest';
import { syncTaxTransactions } from './taxService';
import type { Transaction } from '../types';

const baseFee = (overrides: Partial<Transaction> = {}): Transaction => ({
  id: `fee-${overrides.date ?? '2026-04-15'}-${Math.random().toString(36).slice(2, 8)}`,
  date: '2026-04-15',
  amount: 100000,
  type: 'income',
  group: 'fee',
  category: 'שכר טרחה',
  description: 'לקוח לדוגמה',
  paymentMethod: 'transfer',
  status: 'completed',
  ...overrides,
});

describe('syncTaxTransactions', () => {
  it('creates VAT and income tax records for a single fee month', () => {
    const fees: Transaction[] = [baseFee({ date: '2026-04-15', amount: 549342 })];
    const result = syncTaxTransactions(fees);

    const generated = result.filter(t => t.isAutoGenerated);
    expect(generated).toHaveLength(2);

    const vat = generated.find(t => t.category === 'מע"מ');
    const tax = generated.find(t => t.category === 'מס הכנסה אישי');

    expect(vat).toBeDefined();
    expect(vat!.amount).toBeCloseTo(98881.56, 2); // 18% × 549342
    expect(vat!.date).toBe('2026-05-25');
    expect(vat!.linkedMonth).toBe('2026-04');

    expect(tax).toBeDefined();
    // 14% × NET (549342 / 1.18) for May 2026 payments onwards
    expect(tax!.amount).toBeCloseTo(549342 / 1.18 * 0.14, 2);
    expect(tax!.date).toBe('2026-05-23');
  });

  it('uses 14% × net for ALL months (historical accuracy ensured by isManualOverride on past entries)', () => {
    // Per user's design: the auto-formula is always 14% × net. Pre-May 2026
    // historical accuracy is guaranteed because real past records are
    // marked isManualOverride and never recalculated.
    const fees: Transaction[] = [baseFee({ date: '2026-03-15', amount: 100000 })];
    const result = syncTaxTransactions(fees);
    const tax = result.find(t => t.isAutoGenerated && t.category === 'מס הכנסה אישי');
    expect(tax).toBeDefined();
    expect(tax!.amount).toBeCloseTo(100000 / 1.18 * 0.14, 2);
    expect(tax!.date).toBe('2026-04-23');
  });

  it('does NOT regenerate or duplicate tax records when called repeatedly', () => {
    const fees: Transaction[] = [baseFee({ date: '2026-04-15', amount: 100000 })];
    const first = syncTaxTransactions(fees);
    const second = syncTaxTransactions(first);
    const third = syncTaxTransactions(second);

    const autoCount = (list: Transaction[]) => list.filter(t => t.isAutoGenerated).length;
    expect(autoCount(first)).toBe(2);
    expect(autoCount(second)).toBe(2);
    expect(autoCount(third)).toBe(2);
  });

  it('respects isManualOverride - keeps the user amount intact', () => {
    const fees: Transaction[] = [baseFee({ date: '2026-04-15', amount: 100000 })];
    const synced = syncTaxTransactions(fees);
    // User manually edits the auto-tax to a different value
    const tax = synced.find(t => t.isAutoGenerated && t.category === 'מס הכנסה אישי')!;
    tax.amount = 9999;
    tax.isManualOverride = true;

    const resynced = syncTaxTransactions(synced);
    const taxAfter = resynced.find(t => t.id === tax.id);
    expect(taxAfter!.amount).toBe(9999);
  });

  it('skips fee transactions that are not completed', () => {
    const fees: Transaction[] = [baseFee({ date: '2026-04-15', amount: 100000, status: 'pending' })];
    const result = syncTaxTransactions(fees);
    const auto = result.filter(t => t.isAutoGenerated);
    expect(auto).toHaveLength(0);
  });

  it('skips non-fee income transactions', () => {
    const others: Transaction[] = [
      baseFee({ date: '2026-04-15', amount: 50000, group: 'other_income', category: 'החזר חוב' }),
    ];
    const result = syncTaxTransactions(others);
    const auto = result.filter(t => t.isAutoGenerated);
    expect(auto).toHaveLength(0);
  });

  it('removes auto records when the underlying fee month no longer has income', () => {
    // First create
    const fees1 = [baseFee({ date: '2026-04-15', amount: 100000 })];
    const synced = syncTaxTransactions(fees1);
    expect(synced.filter(t => t.isAutoGenerated)).toHaveLength(2);

    // Now imagine all April fees got deleted - sync again with just the auto records
    const onlyAuto = synced.filter(t => t.isAutoGenerated);
    const cleaned = syncTaxTransactions(onlyAuto);
    expect(cleaned.filter(t => t.isAutoGenerated)).toHaveLength(0);
  });

  it('handles year transitions correctly (December income → January tax)', () => {
    const fees: Transaction[] = [baseFee({ date: '2025-12-20', amount: 100000 })];
    const result = syncTaxTransactions(fees);
    const tax = result.find(t => t.isAutoGenerated && t.category === 'מס הכנסה אישי');
    expect(tax).toBeDefined();
    expect(tax!.date).toBe('2026-01-23');
    // Always 14% × net (per current taxService design)
    expect(tax!.amount).toBeCloseTo(100000 / 1.18 * 0.14, 2);
  });

  it('aggregates multiple fee transactions in the same month', () => {
    const fees: Transaction[] = [
      baseFee({ date: '2026-04-05', amount: 100000 }),
      baseFee({ date: '2026-04-15', amount: 200000 }),
      baseFee({ date: '2026-04-25', amount: 300000 }),
    ];
    const result = syncTaxTransactions(fees);
    const vat = result.find(t => t.isAutoGenerated && t.category === 'מע"מ')!;
    expect(vat.amount).toBeCloseTo(108000, 2); // 18% × 600000
  });

  it('VAT amount uses 18% of gross regardless of tax rate epoch', () => {
    const fees: Transaction[] = [baseFee({ date: '2026-04-15', amount: 100000 })];
    const result = syncTaxTransactions(fees);
    const vat = result.find(t => t.isAutoGenerated && t.category === 'מע"מ')!;
    expect(vat.amount).toBeCloseTo(18000, 2);
  });
});
