export type TransactionType = 'income' | 'expense';

// Updated groups to support split income columns
export type TransactionGroup =
  | 'fee'
  | 'other_income'
  | 'operational'
  | 'tax'
  | 'loan'
  | 'personal'
  | 'bank_adjustment';

export interface Transaction {
  id: string;
  date: string; // ISO date string YYYY-MM-DD
  amount: number;
  type: TransactionType;
  group: TransactionGroup; 
  category: string;
  description: string;
  clientReference?: string; // Optional: Reference to a specific case or client file
  paymentMethod: 'transfer' | 'check' | 'credit_card' | 'cash';
  status: 'pending' | 'completed';
  isRecurring?: boolean; 
  loanEndMonth?: string; // YYYY-MM, when the loan is expected to finish
  
  // New fields for Auto-Tax Logic
  isAutoGenerated?: boolean; // True if created by the system (Tax/VAT)
  linkedMonth?: string; // YYYY-MM : The month this tax payment relates to (e.g. Tax in Feb relates to Jan income)
  isManualOverride?: boolean; // If true, the auto-calculator won't update the amount automatically
}

export interface MonthlySummary {
  totalIncome: number;
  totalExpenses: number;
  netCashFlow: number;
  startBalance: number;
  endBalance: number;
}

export interface Category {
  id: string;
  name: string;
  type: TransactionType;
  group: TransactionGroup;
  color: string;
  defaultAmount?: number; // Optional default amount for auto-fill
  defaultDay?: number;    // Optional default day of month (1-31)
}